[server]
headless = true
port = 8501
enableCORS = false


[theme]
primaryColor = "#4caf50ff"
backgroundColor = "#c9afe0ff"
secondaryBackgroundColor = "#1a87b5ff"
textColor = "#000000"
font = "sans serif"
